import { NextRequest, NextResponse } from 'next/server';
import { Resend } from 'resend';

interface ActionItem {
  task: string;
  owner: string;
  deadline: string | null;
}

interface AlternativeApproach {
  topic: string;
  currentApproach: string;
  alternative: string;
  tradeoff: string;
}

interface Sentiment {
  label: string;
  explanation: string;
}

interface AnalysisResult {
  summary: string;
  actionItems: ActionItem[];
  alternativeApproaches: AlternativeApproach[];
  sentiment: Sentiment;
}

interface Participant {
  name: string;
  email: string;
}

function buildEmailHtml(
  participant: Participant,
  analysis: AnalysisResult,
  questions: string[],
  meetingDate: string,
): string {
  const actionItemsHtml =
    analysis.actionItems && analysis.actionItems.length > 0
      ? `<ul style="margin:0;padding-left:20px;color:#c9d1d9;">
          ${analysis.actionItems
            .map(
              (item) =>
                `<li style="margin-bottom:6px;">${item.task} — ${item.owner}${item.deadline ? ` <span style="color:#8b949e;">(due: ${item.deadline})</span>` : ''}</li>`,
            )
            .join('')}
        </ul>`
      : `<p style="color:#8b949e;font-style:italic;">No action items identified.</p>`;

  const alternativesHtml =
    analysis.alternativeApproaches && analysis.alternativeApproaches.length > 0
      ? analysis.alternativeApproaches
          .map(
            (alt) =>
              `<div style="background:#161b22;border:1px solid #21262d;border-radius:8px;padding:16px;margin-bottom:12px;">
                <p style="margin:0 0 6px 0;font-weight:bold;color:#e6edf3;">Topic: ${alt.topic}</p>
                <p style="margin:0 0 4px 0;color:#8b949e;">Current approach: ${alt.currentApproach}</p>
                <p style="margin:0 0 4px 0;color:#3b82f6;">💡 Alternative: ${alt.alternative}</p>
                <p style="margin:0;color:#c9d1d9;font-style:italic;">Trade-off: ${alt.tradeoff}</p>
              </div>`,
          )
          .join('')
      : `<p style="color:#8b949e;font-style:italic;">No alternative approaches generated.</p>`;

  const questionsHtml =
    questions && questions.length > 0
      ? `<ul style="margin:0;padding-left:20px;color:#c9d1d9;">
          ${questions.map((q) => `<li style="margin-bottom:6px;">${q}</li>`).join('')}
        </ul>`
      : `<p style="color:#8b949e;font-style:italic;">No questions were captured during this meeting.</p>`;

  return `
    <div style="background:#0d1117;font-family:Arial,sans-serif;padding:32px;min-height:100vh;">
      <div style="max-width:640px;margin:0 auto;">

        <!-- Header -->
        <div style="margin-bottom:24px;">
          <p style="margin:0;color:#3b82f6;font-size:24px;font-weight:bold;">VisionNaBiso</p>
          <p style="margin:4px 0 0 0;color:#8b949e;font-size:14px;">${meetingDate}</p>
        </div>

        <div style="border-top:1px solid #21262d;margin-bottom:24px;"></div>

        <!-- Section 1: Summary -->
        <div style="margin-bottom:32px;">
          <h2 style="margin:0 0 12px 0;color:#e6edf3;font-size:18px;">📋 Summary</h2>
          <p style="margin:0;color:#c9d1d9;line-height:1.6;">${analysis.summary}</p>
        </div>

        <!-- Section 2: Action Items -->
        <div style="margin-bottom:32px;">
          <h2 style="margin:0 0 12px 0;color:#e6edf3;font-size:18px;">✅ Action Items</h2>
          ${actionItemsHtml}
        </div>

        <!-- Section 3: AI Suggestions -->
        <div style="margin-bottom:32px;">
          <h2 style="margin:0 0 12px 0;color:#e6edf3;font-size:18px;">💡 AI Suggestions &amp; Alternative Ideas</h2>
          ${alternativesHtml}
        </div>

        <!-- Section 4: Questions -->
        <div style="margin-bottom:32px;">
          <h2 style="margin:0 0 12px 0;color:#e6edf3;font-size:18px;">❓ Questions Raised</h2>
          ${questionsHtml}
        </div>

        <!-- Section 5: Sentiment -->
        <div style="margin-bottom:32px;">
          <h2 style="margin:0 0 12px 0;color:#e6edf3;font-size:18px;">🎭 Meeting Sentiment</h2>
          <p style="margin:0 0 8px 0;">
            <span style="font-weight:bold;text-transform:uppercase;color:#3b82f6;">${analysis.sentiment?.label ?? 'unknown'}</span>
          </p>
          <p style="margin:0;color:#c9d1d9;line-height:1.6;">${analysis.sentiment?.explanation ?? ''}</p>
        </div>

        <!-- Footer -->
        <div style="border-top:1px solid #21262d;margin-top:32px;padding-top:16px;text-align:center;">
          <p style="margin:0;color:#8b949e;font-size:12px;">Generated by VisionNaBiso Intelligence Agent</p>
        </div>

      </div>
    </div>
  `;
}

export async function POST(req: NextRequest) {
  const { participants, callId, analysis, questions, meetingDate } = await req.json();

  if (!process.env.RESEND_API_KEY) {
    console.warn('[email] RESEND_API_KEY is not set — skipping email sends');
    return NextResponse.json({ success: true, sent: 0 });
  }

  const resend = new Resend(process.env.RESEND_API_KEY);

  let sent = 0;
  let failed = 0;

  for (const participant of participants as Participant[]) {
    if (!participant.email || !participant.email.includes('@')) continue;

    try {
      await resend.emails.send({
        from: 'VisionNaBiso <onboarding@resend.dev>',
        to: participant.email,
        subject: `Your Meeting Report — ${meetingDate}`,
        html: buildEmailHtml(participant, analysis, questions, meetingDate),
      });
      console.log('[email] sent to:', participant.email);
      sent++;
    } catch (err) {
      console.error('[email] failed for', participant.email, err);
      failed++;
    }
  }

  return NextResponse.json({ success: true, sent, failed });
}
